# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BankApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BankApp
  pod 'GoogleMaps'
  pod 'RealmSwift'
  pod 'Moya'
  pod 'Moya-ObjectMapper', '2.9'
  pod 'Google-Maps-iOS-Utils', '~> 4.1.0'

end
